### ISSUE TITLE
Gemini api

### ISSUE THREAD

**Issue by VicThor-wpp** [unclecode/crawl4ai#101]
Is there a way to use the free gemini api? 
Its really useful in long context tasks

**Comment by unclecode** [comment]
@VicThor-wpp  Hello, we're using a light LLM in the backend of this library so we can support all these models. You just need to, if you look at our example which uses Open AI, you can pass a Gemini model `gemini/gemini-pro`. And then, if the model requires an API token, you don't need to pass it out of us. For example, if you're using Ollama, yes, you can use it because its lung context is absolutely very good, and we love that too.

**Comment by escoolioinglesias** [comment]
I'm a bit confused, how do you set up `.llm.env` to use the aistudio.google.com API Key to use gemini 2.5 pro ?
