### ISSUE TITLE
Can we make it smart crawler along with sub web crawling ?

### ISSUE THREAD

**Issue by Darshan2104** [unclecode/crawl4ai#131]
Hi, 
Is it possible to do smart crawl integrating LLM agent.

For example, 
along with url, use can pass small instruction what actually user wants from webpage. 

based on instruction, it will search for those information, if requires access hyperlinks and search for information.
and once everything is crawled, it will summarise it based on instruction.

**Comment by unclecode** [comment]
Hello Darshan, that's a very intriguing suggestion. Actually, in our backlog, we do have the phase to start agenetic behavior for our crawler. Before that, we want to make sure that corse crawler is solid and robust enough in this. And then, after that, we are working on a scrapper engine, which is going to be released within a few weeks. Once everything is ready, there will be no issues, and we want to move to agenetic crawler. 

Right now you use the LLMExtractionStrategy, pass some instructions, but those instructions will only be used for extracting data that you want; they will not handle execution or managing actions for our future plan. 

We're working on coming up with a beautiful design and a clear plan to handle what we discussed just right now, which will allow you to create different JavaScript functions. We view these functions as tools that we will let the AI agent use to decide which function should be called within the browser session. These functions can be for extraction, applying actions, or basically moving towards pages. At a higher level, we will let the main agent decide whether to execute this search and if it should come in or not. We can also have multiple agents. 

This is our current backlog. We hope to reach a point where the crawler itself is solid or the scrapper engine is strong, and then we can move forward with agentic crawling again. Thank you so much, and please stay tuned; that's exactly what we're going to do.

**Comment by Darshan2104** [comment]
Hi @unclecode, agenetic crawler is gonna be a next level thing. If you have any project planning regarding that, I would love to contribute.

**Comment by unclecode** [comment]
@Darshan2104 you are most welcome, please she with me your email address then I send discord invitation.

**Comment by Darshan2104** [comment]
Sure, it is tankdarshan01@gmail.com

**Comment by unclecode** [comment]
@Darshan2104 I will send invitation link this weekend, thx.

**Comment by unclecode** [comment]
@Darshan2104 Hi Darshan, sorry for the delay, I just send the invitation link to you, looking forward to see you on the other side.

**Comment by abhirup-dev** [comment]
@aravindkarnam @unclecode would love to contribute on whole-blog crawling: I'm looking for something similar for a project.
Please feel free to ping on [dev.abhirupdas@gmail.com](mailto:dev.abhirupdas@gmail.com) if you would like to share discord invite.

**Comment by unclecode** [comment]
@Darshan2104 right now u can use LLMExtractionStrategy, This strategy isn’t just for extracting structured data—it actually takes an instruction parameter, where you can specify exactly what you want.

For example, you could instruct it to summarize the page, extract only specific data items based on a semantical query (like positive comments focus on a specific features), or do anything else you’d expect from a language model.

**Smart Crawling vs. Standard Crawling**

If by smart crawling, you mean using an LLM to process content in the way I explained then yes, you can already use LLM extraction.

However, when I talk about smart crawlers, I mean something more agentic—where the crawler is given an objective rather than just a predefined extraction rule.

For example, if you’re searching for specific products, a smart crawler would:
	1.	Start from a homepage and try to predict where the relevant data might be.
	2.	Think and decide whether to execute JavaScript, such as clicking buttons or dynamically loading content, and will generate code if is needed.
	3.	Navigate through pages to satisfy the initial objective, rather than just extracting from a known structure.

This kind of agentic crawling is on our roadmap.

So you can already achieve what you’re asking for using LLM-based extraction. I might even create a tutorial on this. In fact, I think we already have an example in the examples folder, where we build a knowledge graph from a webpage.

That example doesn’t just extract structured data—it uses an LLM to create a different kind of output, which is similar to what you’re describing. I recommend checking that out!

**Comment by unclecode** [comment]
@abhirup-dev  Definitely! We’d be more than happy to have enthusiastic people join our community and contribute. You’re most welcome!

@aravindkarnam, please assist here. Thank you!
