### ISSUE TITLE
[Request] Docker Deployment of the Latest Version of Crawl4ai and a Guide to Using the REST API

### ISSUE THREAD

**Issue by socekin** [unclecode/crawl4ai#138]
Hi, there , Is there a Docker deployment version of Crawl4ai and a usage method for the REST API?

**Comment by unclecode** [comment]
Hello, yes, there have been some changes and we have moved from the synchronous version to an asynchronous version. That's why we need to rewrite the Docker. Hopefully, by next week, we will be able to upload the Docker as well, and you will also have access to the REST API server, which is currently in our plan.
