### ISSUE TITLE
Error while taking the Screenshot

### ISSUE THREAD

**Issue by nandhu-nr** [unclecode/crawl4ai#159]
[<ipython-input-11-c7a674064c44>](https://localhost:8080/#) in main()
      5         result = await crawler.arun(url="https://www.nbcnews.com/business", screenshot=True)
      6         with open("screenshot.png", "wb") as f:
----> 7             f.write(base64.b64decode(result.screenshot))
      8         print("Screenshot saved to 'screenshot.png'!")

[/usr/lib/python3.10/base64.py](https://localhost:8080/#) in b64decode(s, altchars, validate)
     78     in the input result in a binascii.Error.
     79     """
---> 80     s = _bytes_from_decode_data(s)
     81     if altchars is not None:
     82         altchars = _bytes_from_decode_data(altchars)

[/usr/lib/python3.10/base64.py](https://localhost:8080/#) in _bytes_from_decode_data(s)
     43         return memoryview(s).tobytes()
     44     except TypeError:
---> 45         raise TypeError("argument should be a bytes-like object or ASCII "
     46                         "string, not %r" % s.__class__.__name__) from None
     47 

TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'

**Comment by unclecode** [comment]
Hi @nandhu-nr  This bug has been resolved. By tomorrow or the following day, when version 0.3.6 is released, you can use it without any issues. I have also updated the example folder, where you can find some examples. Additionally, I have shared the code with you. If you are running short on time, you can pull the branch "0.3.6" and use it immediately. Otherwise, please wait a day or two, and you will have access to the latest version.

```python

async def capture_and_save_screenshot(url: str, output_path: str):
    async with AsyncWebCrawler(verbose=True) as crawler:
        result = await crawler.arun(
            url=url,
            screenshot=True,
            bypass_cache=True
        )
        
        if result.success and result.screenshot:
            import base64
            
            # Decode the base64 screenshot data
            screenshot_data = base64.b64decode(result.screenshot)
            
            # Save the screenshot as a JPEG file
            with open(output_path, 'wb') as f:
                f.write(screenshot_data)
            
            print(f"Screenshot saved successfully to {output_path}")
        else:
            print("Failed to capture screenshot")
```

I close the issue, but you are welcome to continue if you need any help/
