### ISSUE TITLE
Detect different failures cases

### ISSUE THREAD

**Issue by si2w** [unclecode/crawl4ai#206]
It would be useful as well to detect pages with: 
- Captcha
- Bot wall
- Please update your browser
- Parked domain
- ... 

Those errors are already handled if I'm not wrong : 
- HTTP errors (4xx, 5xx)
- TLS issue

**Comment by unclecode** [comment]
Thank you for using our library. I suggest you check this issue, https://github.com/unclecode/crawl4ai/issues/214, I've added a new feature that's likely the best way to handle such things by taking control of your own browser instead of the default one. You can also pass user data folder and do a lot of things. Additionally, we've added some features to help with this process. Please check and let me know if it's helpful.

**Comment by unclecode** [comment]
I closed this issue, but you can continue the conversation here or in issue #214.
