### ISSUE TITLE
how to crawl blocked website

### ISSUE THREAD

**Issue by QuangTQV** [unclecode/crawl4ai#225]
Please enable cookies.\n\n# Sorry, you have been blocked\n\n## You are unable to access gitbook.io\n\n## Why have I been blocked?\n\nThis website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.\n\n## What can I do to resolve this?\n\nYou can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.\n\nCloudflare Ray ID: **8dd30bf4ed72ce4f** • Your IP: Click to reveal 12x.xxx.xxx • Performance & security by Cloudflare

I crawled the site and it was blocked, how do I fix it?

**Comment by chris-garrett** [comment]
ive run into similar issues even with Magic on. today i learned about playwrights stealth project and this python port: https://github.com/AtuboDad/playwright_stealth.  

```
from playwright_stealth import stealth_async

async def before_goto(page: Page):
    await stealth_async(page)  <--- this is the magic
    return page
    
crawler_strategy = AsyncPlaywrightCrawlerStrategy(
    verbose=True,
    headless=False,
)
crawler_strategy.set_hook("before_goto", before_goto)    

async with AsyncWebCrawler(
    verbose=True,
    always_by_pass_cache=True,
    crawler_strategy=crawler_strategy,
) as crawler:
  ...
```

**Comment by unclecode** [comment]
@QuangTQV @chris-garrett Since the day this issue was created, around a week ago, a bunch of changes have been added to the library. We already had stealth mode inside the library, so when you set magic to it now, it uses that one. There's also a specific flag to use it. Now, we have managed browsers that allow you to pass a user data directory, which almost crosses all limits. By building up a profile for yourself and using it, this issue is explained in detail. I think this will almost fix the majority of requirements for places that may block. Please check this issue https://github.com/unclecode/crawl4ai/issues/238 We can move the discussion over there
