### ISSUE TITLE
Scraping linked URLs

### ISSUE THREAD

**Issue by QuangTQV** [unclecode/crawl4ai#241]
Is there an optimized way to scrape linked URLs on a website, ensuring that only necessary links are scraped (same domain, not scraping ad links), and avoiding duplicate links (if a link has already been scraped, do not scrape it again)? The speed must be optimized.

**Comment by unclecode** [comment]
Hi, @QuangTQV  thank you for using the library. You're right, which is why we're dropping a scrapper module soon, prioritizing efficiency. We support different algorithms and strategies, bringing various filters and techniques for optimized crawling and scraping. For now, it's under testing and review, but we hope to have it ready within weeks, likely before year-end. Currently, we have a perfect way to crawl any URL and produce a good markdown. We also have the ability to crawl multiple URLs simultaneously via parallelism, though this isn't full scraping. The upcoming scrapper will address issues like duplication avoidance and speed optimization, as well as memory and CPU usage. Stay tuned for its release.

**Comment by QuangTQV** [comment]
> Hi, @QuangTQV thank you for using the library. You're right, which is why we're dropping a scrapper module soon, prioritizing efficiency. We support different algorithms and strategies, bringing various filters and techniques for optimized crawling and scraping. For now, it's under testing and review, but we hope to have it ready within weeks, likely before year-end. Currently, we have a perfect way to crawl any URL and produce a good markdown. We also have the ability to crawl multiple URLs simultaneously via parallelism, though this isn't full scraping. The upcoming scrapper will address issues like duplication avoidance and speed optimization, as well as memory and CPU usage. Stay tuned for its release.

Is this feature available in version 0.3.74? @unclecode

**Comment by QuangTQV** [comment]
> Hi, @QuangTQV thank you for using the library. You're right, which is why we're dropping a scrapper module soon, prioritizing efficiency. We support different algorithms and strategies, bringing various filters and techniques for optimized crawling and scraping. For now, it's under testing and review, but we hope to have it ready within weeks, likely before year-end. Currently, we have a perfect way to crawl any URL and produce a good markdown. We also have the ability to crawl multiple URLs simultaneously via parallelism, though this isn't full scraping. The upcoming scrapper will address issues like duplication avoidance and speed optimization, as well as memory and CPU usage. Stay tuned for its release.

I'm looking to build a chatbot for any given URL, so I need a function to crawl all useful information from a URL. For example, with a sales chatbot, it would start from the homepage and navigate to relevant sub-links to crawl product information. Crawlee already provides this functionality (https://crawlee.dev/python/docs/introduction/adding-more-urls), and I am eagerly looking forward to crawl4AI.
