### ISSUE TITLE
When crawling Twitter, fit_markdown doesn't pick up the content, but markdown does.

### ISSUE THREAD

**Issue by JoysKang** [unclecode/crawl4ai#284]
I was using crawl4ai for Twitter content crawling and wanted to go for content analysis. I found that fit_markdown returns only the Twitter account and nothing else. But markdown can return data normally.

The code is as follows.

```
async def twitter_main():
    schema = {
        "name": "Twitter",
        "baseSelector": "[data-testid='tweet']",
        "fields": [
        ]
    }

    wait_for = """() => {
        const tweetExists = document.querySelector("[data-testid='tweet']") !== null;
        const reloadTextExists = Array.from(document.querySelectorAll('div span'))
            .some(span => span.textContent.includes('Try reloading'));
        return tweetExists || reloadTextExists;
    }"""


    async with AsyncWebCrawler(verbose=True) as crawler:
        urls = ['https://x.com/YSI_crypto/status/1771010742059504127?s=20']
        result = await crawler.arun_many(urls=urls, 
                                         extraction_strategy=JsonCssExtractionStrategy(schema, verbose=False),
                                         wait_for=wait_for,
                                         bypass_cache=True,
                                         css_selector=schema["baseSelector"],
                                         )

        for r in result:
            print(r.markdown)
            print("----")
            print(r.fit_markdown)


asyncio.run(twitter_main())
```

**Comment by unclecode** [comment]
Hi @JoysKang, 

Thanks for trying Crawl4AI! Regarding the `fit_markdown` feature, it’s currently experimental. Here’s how it works:

1. **Head Section Analysis**:  
   The algorithm checks if the HTML has a `<head>` section. If present, it extracts the title, meta tags, descriptions, and keywords.

2. **Content Retrieval**:  
   It uses the BM25 scoring algorithm to identify and rank content on the page based on relevance to these extracted details. Essentially, it performs a content retrieval task.

### Why It Didn't Work in Your Case

- You’re passing a specific HTML snippet for an article, but that snippet doesn’t have a `<head>` section or metadata (like a title or meta description).  
- As a result, `fit_markdown` doesn’t return anything. Even if it did, the output would likely match your input markdown because there’s no broader context to process.

### How to Improve Results

- **User Query Parameter**:  
   You can pass a user query in situations where there’s no `<head>` section or metadata. This allows the algorithm to use the query as its primary context.  
   
- **BM25 Threshold**:  
   Adjust the BM25 threshold (default is `1`). Lowering it can help retrieve more results.

Here’s an example code snippet I tested on a full page (e.g., Wikipedia), which might give you a better understanding:

```python
async def main():
    async with AsyncWebCrawler(
        verbose=True,
        headless=False,
        ) as crawler:
        # url = "https://x.com/YSI_crypto/status/1771010742059504127?s=20"
        url = "https://en.wikipedia.org/wiki/Apple"
        result = await crawler.arun(
            url=url,
            # extraction_strategy=JsonCssExtractionStrategy(schema, verbose=False),
            cache_mode=CacheMode.ENABLED,
            # css_selector=schema["baseSelector"],
            delay_before_return_html = 5.0,
            content_filter=BM25ContentFilter(
                # user_query="pass your desried query"
                # bm25_threshold=1,                
            ),
        )
        
        with open(f"{__location__}/output/raw.md", "w") as f:
            f.write(result.markdown_v2.raw_markdown)

        with open(f"{__location__}/output/fit.md", "w") as f:
            f.write(result.markdown_v2.fit_markdown)

        print(len(result.markdown_v2.raw_markdown))
        print(len(result.markdown_v2.fit_markdown))

if __name__ == "__main__":
    asyncio.run(main())
```

Also, as you noticed, there are a few other things that I changed in your code because you can achieve the same thing in a simpler way. And also, if you're interested, you can explain to me your case study. I may be able to write down a good way of using the library to help you, and then from there you can continue.

### Final Notes

This feature is still in its early stages of development, so it’s not the final implementation. Feel free to reach out if you encounter more issues or need further assistance.

**Comment by JoysKang** [comment]
Understood, thank you for clarifying.

I will close this issue.

**Comment by unclecode** [comment]
@JoysKang you are most welcome

**Comment by mohamed-nasser-1** [comment]
@JoysKang Is it still under experimentation?
