### ISSUE TITLE
 can excluded  by css_selector?

### ISSUE THREAD

**Issue by lexang** [unclecode/crawl4ai#296]
I have selected a piece of content based on a CSS selector, and there are several identical CSS selectors within this content that I don't need: <div class="code-block">. How can I do this? Is this supported now? If not, will it be supported in the future? When will it be supported?

**Comment by unclecode** [comment]
@lexang Thanks for trying our library. Would you please share your code with me? But let me take a look. There are ways that you can focus on one of them, or you can extract all of them. Let me see your code, and then I will be able to help you.

**Comment by duolaOmeng** [comment]
Hello, I want to use the css_selector parameter to select the content I want, but after setting this parameter there is no effect.Can I refer to your code?

**Comment by unclecode** [comment]
@duolaOmeng I noticed another issue that you posted because you faced something similar with someone else. I share the same code here. Just remember that when you use a CSS selector, you are subject to the situation where, at the moment the crawler checks for the existence of the element, the element may not be rendered yet. This can happen on some websites. One way to address this is to add a `wait_for` the same CSS selector that you use. Look at the following code.

```python
async def main():
    config = BrowserConfig(
        headless=True,
    )

    async with AsyncWebCrawler(config=config) as crawler:
        crawl_config = CrawlerRunConfig(
            cache_mode=CacheMode.BYPASS,
            css_selector=".api-detail",
            excluded_tags=['form', 'nav','footer'],
            wait_for="css:.api-detail",
            # delay_before_return_html=2
        )
        result = await crawler.arun(
            url="https://doc.youzanyun.com/detail/API/0/323",
            config=crawl_config
        )
        print(result.markdown)

if __name__ == "__main__":
    asyncio.run(main())
```
