### ISSUE TITLE
Confused about returned data

### ISSUE THREAD

**Issue by JElliott3630** [unclecode/crawl4ai#310]
I am trying to parse and return the href links of the current trending repositories in github using html parsing.
When I use the requests library, I get up to date information consistently.
When I use crawl4ai, it returns what I think might have even been yesterdays data. Is there a problem with my code?
Pasting crawl4ai script:

import asyncio
from crawl4ai import AsyncWebCrawler
from bs4 import BeautifulSoup

async def main():
    async with AsyncWebCrawler(verbose=True) as crawler:
        # Load and wait for the trending repositories
        result = await crawler.arun(
            url="https://github.com/trending",
            clear_cache=True,
            page_timeout=60000,
            wait_for="css:article.Box-row"  # Wait for repository rows to appear
        )
        
        # Parse the content with BeautifulSoup
    soup = BeautifulSoup(result.html, 'html.parser')
    
    # Extract trending repositories
    repos = []
    table = soup.select_one("div.position-relative.container-lg.p-responsive.pt-6 > div > div:nth-child(2)")
    if table:
        rows = table.select("article.Box-row")
        for row in rows:
            h2_element = row.find("h2", class_="h3 lh-condensed")
            description = row.find("p")
            if h2_element:
                link = h2_element.find("a")["href"]
                repos.append({
                    "name": h2_element.get_text(strip=True),
                    "link": f"https://github.com{link}",
                    "description": description.get_text(strip=True) if description else ""
                })
    
    # Print extracted repositories
    for repo in repos:
        print(repo)

# Run the async main function
asyncio.run(main())

**Comment by unclecode** [comment]
@JElliott3630 It appears you’re seeing stale results because the response is coming from crawl4ai’s cache rather than fetching fresh data every time. In your snippet, `clear_cache=True` isn’t a recognized parameter by the crawler and thus isn’t affecting caching behavior.

You should use the new caching parameters introduced in recent versions of crawl4ai. For example, you can explicitly bypass the cache by specifying:

```python
from crawl4ai.cache_context import CacheMode

result = await crawler.arun(
    url="https://github.com/trending",
    cache_mode=CacheMode.BYPASS,
    page_timeout=60000,
    wait_for="css:article.Box-row"
)
```

This ensures that the crawler always fetches the latest version of the page, instead of serving from a previously saved cache.
