### ISSUE TITLE
How to crawl new content after click a button

### ISSUE THREAD

**Issue by lxb1202** [unclecode/crawl4ai#336]
Thanks for your good project for crawler @unclecode , it is wonderful. 😘

Here is a function I want to implement, but don't know how to do, so want to find a solution.

I want to crawl a page, and this page have 20 modules that need to be clicked to update. I need to click 'next' button, then the page will get new content (in the same website). So I want to ask: how can I do this click action and then get the new content? 👀

Yours sincerely.

**Comment by unclecode** [comment]
@lxb1202 Thank you so much for trying to crawl for AI, and I'm happy that you have fun with it. Your question is actually a typical one, because other people ask similar questions about how to retrieve information in that way. So, I decided to create a short tutorial, which I put here for you, and later I will also add it to my blog to help other people as well. Thank you for your good question.

# Tutorial: Clicking Buttons to Load More Content with Crawl4AI

## Introduction

When scraping dynamic websites, it’s common to encounter “Load More” or “Next” buttons that must be clicked to reveal new content. Crawl4AI provides a straightforward way to handle these situations using JavaScript execution and waiting conditions. In this tutorial, we’ll cover two approaches:

1. **Step-by-step (Session-based) Approach:** Multiple calls to `arun()` to progressively load more content.
2. **Single-call Approach:** Execute a more complex JavaScript snippet inside a single `arun()` call to handle all clicks at once before the extraction.

## Prerequisites

- A working installation of Crawl4AI
- Basic familiarity with Python’s `async`/`await` syntax

## Step-by-Step Approach

Use a session ID to maintain state across multiple `arun()` calls:

```python
from crawl4ai import AsyncWebCrawler, CacheMode

js_code = [
    # This JS finds the “Next” button and clicks it
    "const nextButton = document.querySelector('button.next'); nextButton && nextButton.click();"
]

wait_for_condition = "css:.new-content-class"

async with AsyncWebCrawler(headless=True, verbose=True) as crawler:
    # 1. Load the initial page
    result_initial = await crawler.arun(
        url="https://example.com",
        cache_mode=CacheMode.BYPASS,
        session_id="my_session"
    )

    # 2. Click the 'Next' button and wait for new content
    result_next = await crawler.arun(
        url="https://example.com",
        session_id="my_session",
        js_code=js_code,
        wait_for=wait_for_condition,
        js_only=True,
        cache_mode=CacheMode.BYPASS
    )

# `result_next` now contains the updated HTML after clicking 'Next'
```

**Key Points:**
- **`session_id`**: Keeps the same browser context open.
- **`js_code`**: Executes JavaScript in the context of the already loaded page.
- **`wait_for`**: Ensures the crawler waits until new content is fully loaded.
- **`js_only=True`**: Runs the JS in the current session without reloading the page.

By repeating the `arun()` call multiple times and modifying the `js_code` (e.g., clicking different modules or pages), you can iteratively load all the desired content.

## Single-call Approach

If the page allows it, you can run a single `arun()` call with a more elaborate JavaScript snippet that:
- Iterates over all the modules or "Next" buttons
- Clicks them one by one
- Waits for content updates between each click
- Once done, returns control to Crawl4AI for extraction.

Example snippet:

```python
from crawl4ai import AsyncWebCrawler, CacheMode

js_code = [
    # Example JS that clicks multiple modules:
    """
    (async () => {
      const modules = document.querySelectorAll('.module-item');
      for (let i = 0; i < modules.length; i++) {
        modules[i].scrollIntoView();
        modules[i].click();
        // Wait for each module’s content to load, adjust 100ms as needed
        await new Promise(r => setTimeout(r, 100));
      }
    })();
    """
]

async with AsyncWebCrawler(headless=True, verbose=True) as crawler:
    result = await crawler.arun(
        url="https://example.com",
        js_code=js_code,
        wait_for="css:.final-loaded-content-class",
        cache_mode=CacheMode.BYPASS
    )

# `result` now contains all content after all modules have been clicked in one go.
```

**Key Points:**
- All interactions (clicks and waits) happen before the extraction.
- Ideal for pages where all steps can be done in a single pass.

## Choosing the Right Approach

- **Step-by-Step (Session-based)**: 
  - Good when you need fine-grained control or must dynamically check conditions before clicking the next page.
  - Useful if the page requires multiple conditions checked at runtime.

- **Single-call**:
  - Perfect if the sequence of interactions is known in advance.
  - Cleaner code if the page’s structure is consistent and predictable.

## Conclusion

Crawl4AI makes it easy to handle dynamic content:
- Use session IDs and multiple `arun()` calls for stepwise crawling.
- Or pack all actions into one `arun()` call if the interactions are well-defined upfront.

This flexibility ensures you can handle a wide range of dynamic web pages efficiently.

**Comment by lxb1202** [comment]
Thanks for your hard work, it solve my problem. Looking forward to your tutorial. 😋

**Comment by unclecode** [comment]
You are very welcome

**Comment by Hnam29** [comment]
@unclecode Hi, thank you for making the greatest open-source crawler ever. I encountered the issue about clicking on the button and crawling new content, and I failed to crawl after trying both approaches as you provided. Could you please look at the url (https://cafef.vn/du-lieu/tin-doanh-nghiep/vnd/event.chn) and do a quick search? Thanks in advance.

**Comment by unclecode** [comment]
@Hnam29 thx for nice words, sure I check. @aravindkarnam take a peek at it plz

**Comment by Hnam29** [comment]
Thx @unclecode, @aravindkarnam. Really looking forward to your solution 😇

**Comment by aravindkarnam** [comment]
@Hnam29 Sorry! I didn't get a chance to check this issue yet. We were caught up with getting version 0.5 release ready. I will check this today. Actually can you share with me a code snippet, that I can quickly run to assess what you are trying to do with `https://cafef.vn/du-lieu/tin-doanh-nghiep/vnd/event.chn`

**Comment by Hnam29** [comment]
Yes @aravindkarnam, here is the code: 
import asyncio
import json
from datetime import datetime
from urllib.parse import urljoin
from crawl4ai.extraction_strategy import JsonCssExtractionStrategy
from crawl4ai import AsyncWebCrawler, CacheMode, CrawlerRunConfig

async def extract():
    current_time = datetime.now().strftime('%Y%m%d%H%M')
    filename = f"{current_time}_data.json"
    base_url = 'https://cafef.vn' 

    # Define the schema for the articles page extraction
    schema_main = {
        "name": "Article",
        "baseSelector": "#divEvents > ul > li",  
        "fields": [
            {"name": "TITLE", "selector": "a.docnhanhTitle", "type": "text"},
            {"name": "LINK", "selector": "a.docnhanhTitle", "type": "attribute", "attribute": "href"},
            {"name": "TIME", "selector": "span.timeTitle", "type": "text"},
        ],
    }

    # Define the schema for the article detail extraction
    schema_article = {
        "name": "ArticleDetail",
        "baseSelector": "body",
        "fields": [
            {"name": "PARAGRAPHS", "selector": "p", "type": "text"},
        ],
    }

    main_extraction_strategy = JsonCssExtractionStrategy(schema_main, verbose=True)
    article_extraction_strategy = JsonCssExtractionStrategy(schema_article, verbose=True)

    article_details = []
    session_id = "cff_session"  

    async with AsyncWebCrawler(headless=True, verbose=True) as crawler:
        # Step 1: Load the initial page with the main articles using the session id
        config_initial = CrawlerRunConfig(
            cache_mode=CacheMode.BYPASS,
            extraction_strategy=main_extraction_strategy,
            session_id=session_id
        )
        result_initial = await crawler.arun(
            url='https://cafef.vn/du-lieu/tin-doanh-nghiep/vnd/event.chn',
            config=config_initial,
        )

        # Step 2: Click the "Next" button to load more content using js_only
        js_click_next = [
            "const nextButton = document.querySelector('#spanNext'); nextButton && nextButton.click();"
        ]
        wait_for_condition = "css:#divEvents > ul > li"  
        config_click = CrawlerRunConfig(
            cache_mode=CacheMode.BYPASS,
            session_id=session_id,
            js_code=js_click_next,
            wait_for=wait_for_condition,
            js_only=True
        )
        result_click = await crawler.arun(
            url='https://cafef.vn/du-lieu/tin-doanh-nghiep/vnd/event.chn',
            config=config_click,
        )

        # Step 3: Re-run extraction on the updated page with new content loaded
        config_updated = CrawlerRunConfig(
            cache_mode=CacheMode.BYPASS,
            extraction_strategy=main_extraction_strategy,
            session_id=session_id
        )
        result_updated = await crawler.arun(
            url='https://cafef.vn/du-lieu/tin-doanh-nghiep/vnd/event.chn',
            config=config_updated,
        )
        articles = json.loads(result_updated.extracted_content)

        # Process each article for details
        for index, article in enumerate(articles):
            title = article.get("TITLE")
            relative_link = article.get("LINK")
            # Convert relative URL to absolute using urljoin
            link = urljoin(base_url, relative_link)
            time = article.get("TIME")
            is_even = (index % 2 == 0)

            # JS snippet to wait until paragraphs are loaded on the detail page
            js_wait_for_content = """
            (async () => {
                let maxRetries = 10;
                let retries = 0;
                while (retries < maxRetries) {
                    if (document.querySelectorAll('p').length > 0) break;
                    await new Promise(resolve => setTimeout(resolve, 1000));
                    retries++;
                }
            })();
            """
            config_article = CrawlerRunConfig(
                cache_mode=CacheMode.BYPASS,
                extraction_strategy=article_extraction_strategy,
                js_code=[js_wait_for_content],
                session_id=session_id
            )
            try:
                result_article = await crawler.arun(
                    url=link,
                    config=config_article,
                )
                if not result_article.extracted_content:
                    print(f"[ERROR] No content extracted from: {link}")
                    continue

                paragraphs = json.loads(result_article.extracted_content)
                full_content = " ".join([p["PARAGRAPHS"] for p in paragraphs if p["PARAGRAPHS"]])

                article_details.append({
                    "TITLE": title,
                    "LINK": link,
                    "TIME": time,
                    "CONTENT": full_content,
                    "ROW_TYPE": "even" if is_even else "odd",
                })

            except Exception as e:
                print(f"[ERROR] Failed to process link {link}: {e}")

    with open(filename, "w", encoding="utf-8") as json_file:
        json.dump(article_details, json_file, ensure_ascii=False, indent=4)

asyncio.run(extract()) 

There are 2 issues that I am currently stuck in:
1. The pagination (click on the 'next' button) did not work, so I can only get the article/event on the 1st page.
2. The crawler did not go to the article/event link to get the text of p tags (detailed content of the article/event).

I'm really appreciate for your help!

**Comment by Hnam29** [comment]
> [@Hnam29](https://github.com/Hnam29) Sorry! I didn't get a chance to check this issue yet. We were caught up with getting version 0.5 release ready. I will check this today. Actually can you share with me a code snippet, that I can quickly run to assess what you are trying to do with `https://cafef.vn/du-lieu/tin-doanh-nghiep/vnd/event.chn`

I apologize for any inconvenience, but could you please assist me with the code issue?

**Comment by aravindkarnam** [comment]
@Hnam29 I see that this is a duplicate of already open issue. I've replied there and we can continue this discussion there.
