### ISSUE TITLE
Unable to install using git repo url or setting

### ISSUE THREAD

**Issue by shivkumar0757** [unclecode/crawl4ai#36]
error logs: 

python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\shivk\AppData\Local\Temp\pip-req-build-dkiz1hge\setup.py", line 31, in <module>
          long_description=open("README.md").read(),
                           ^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\shivk\.conda\envs\crawl4ai_new\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 25: character maps to <undefined>
      [end of output]

**Comment by unclecode** [comment]
@shivkumar0757  Sorry for the long-delayed response. I believe I missed your issue. Since the day you posted until today, there have been tons of changes to the library. I'm very happy to see that we've faced a lot of interest, requests, and issues, and we're almost 14,000 stars. The entire project has been migrated to an asynchronous version. Here's a sample of the code that you can run quickly, and installation should be much easier than before. You can install using `pip install crawl4ai`. We've resolved many of the conflict issues. Please feel free to let me know if you encounter any problems.

```python
from crawl4ai import AsyncWebCrawler
async def simple_crawl():
    print("\n--- Basic Usage ---")
    async with AsyncWebCrawler(verbose=True) as crawler:
        result = await crawler.arun(url="https://www.nbcnews.com/business")
        print(result.markdown[:500]) 
```
