### ISSUE TITLE
problem running quickstart file

### ISSUE THREAD

**Issue by YitaoLiu1996** [unclecode/crawl4ai#7]
In line 86, self.service = Service(chromedriver_autoinstaller.install())
An exception has occurred: 
ValueError: No chrome executable found on PATH

**Comment by unclecode** [comment]
Please share your system details, OS, CPU (intel or silicon), also, try to run the code below, see if you get any error and if you get then which line is it.

```
from selenium import webdriver
import chromedriver_autoinstaller

chromedriver_autoinstaller.install()  

driver = webdriver.Chrome()
driver.get("http://www.python.org")
assert "Python" in driver.title
```

**Comment by unclecode** [comment]
The error "No chrome executable found on PATH" occurs because the `chromedriver_autoinstaller` package cannot find the Google Chrome executable in the system's PATH. This typically means that Google Chrome is not installed or the PATH environment variable does not include the directory where Chrome is installed.

To resolve this issue on WSL2, follow these steps:

1. **Install Google Chrome on WSL2:**

   ```
   wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
   sudo apt update
   sudo apt install ./google-chrome-stable_current_amd64.deb
   ```

2. **Add Google Chrome to PATH:**

   Ensure Chrome is in your PATH by running:

   ```
   which google-chrome
   ```

   If it is not in your PATH, you can add it manually by editing your `.bashrc` or `.zshrc` file and adding the following line:

   ```
   export PATH=$PATH:/usr/bin/google-chrome
   ```

   After adding this line, run:

   ```
   source ~/.bashrc  # or source ~/.zshrc
   ```

3. **Verify Chrome Installation:**

   Verify that Chrome is correctly installed and accessible from your terminal:

   ```
   google-chrome --version
   ```

4. **Retry your script:**

   Now, try running your Python script again. The `chromedriver_autoinstaller.install()` function should now be able to find the Chrome executable and proceed without errors.

### Full Example Code

Here is a complete example script, assuming you have installed Google Chrome and added it to your PATH:

  ```
   import chromedriver_autoinstaller
   from selenium import webdriver

   # Automatically download and install chromedriver
   chromedriver_autoinstaller.install()

   # Set up WebDriver
   driver = webdriver.Chrome()

   # Your web scraping code here
   driver.get("http://www.example.com")
   print(driver.title)

   driver.quit()
  ```

This should resolve the issue with `chromedriver_autoinstaller.install()`. Let me know if you encounter any further problems!

**Comment by YitaoLiu1996** [comment]
Problem solved! Thank you very much!
