### ISSUE TITLE
Selenium driver apparently is not using the selenium manager -- found old selenium driver and fails to start - also Requirements file not compatible with Python 12

### ISSUE THREAD

**Issue by steelliberty** [unclecode/crawl4ai#74]
Hi -- 

I am anxious to try crawl4ai  But had some problems installing.

When I try to install the requirements file with Python 12, it fails because distutils has been removed from 12. I reinstalled Python 11 and was not able to install Numpy 1.25, so I installed the latest. 

Then, the Selenium Chrome driver on my machine was located as an old one. I gave up on specific Chrome drivers for my crawling projects and started using the manager, which usually determines the required driver. I have yet to look at your code, but chrome drivers are my continual problem. 

i am using the below code to get past continually changing drivers. 

from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))

**Comment by unclecode** [comment]
Hi @steelliberty, thanks for trying Crawl4ai! Currently, we're not using "webdriver_manager" since it's built into Selenium 4.10.0 and above. You can see the code referencing the manager commented out in the `crawl_strategy.py` file. Regarding the Python version, it’s a bit unusual; please check your system specs. Additionally, in the new version, Numpy is not needed for the default mode. Have you tried our Colab? https://colab.research.google.com/drive/1sJPAmeLj5PMrg2VgOwMJ2ubGIcK0cJeX?usp=sharing
